# permissions for end users to edit imagepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepolicy-editor-role
rules:
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagepolicies/status
  verbs:
  - get
