apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  interval: 5m0s
  chart:
    spec:
      chart: alertmanager
      version: "1.27.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  targetNamespace: monitoring
  values:
    replicaCount: 1
    service:
      type: ClusterIP
    automountServiceAccountToken: false
    extraArgs:
      - "--web.enable-lifecycle=true"
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: alertmanager.mangale.com.np
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: alertmanager-tls
          hosts:
            - alertmanager.mangale.com.np
    configmapReload:
      enabled: true
      name: configmap-reload

    receivers:
    - name: default-receiver
      email_configs:
      - to: 'mangal.lopchan@digitalnetwork.com.np'
        send_resolved: true
        # --- ADD THESE TWO LINES ---
        subject: '{{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'
    extraVolumeMounts:
    - name: templates-volume
      mountPath: /etc/alertmanager
      readOnly: true
    extraVolumes:
    - name: templates-volume
      configMap:
        name: alertmanager-email-template
