apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: ">=0.9.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    installCRDs: true
    leaderElect: true
    webhook:
      create: true
    certController:
      create: true
