apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DATABASE_URL: "postgresql://postgres:postgres@db.app-namespace.svc.cluster.local:5432/appdb"