apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: smart-ai
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: smart-ai
  policy:
    semver:
      range: ">=2.0.0"
