apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: smart-ai
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: smart-ai
  policy:
    alphabetical:
      order: desc
  filterTags:
    pattern: '^[a-f0-9]{7}$|^latest$'  # Accept commit hashes OR latest tag
    extract: '$0'
