apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/crds
  - ../base/namespaces/ykp-system
  - ../base/image-automation
  - ../base/metrics-server
  - ../base/gitea
  - ../base/monitoring
  - ../base/cert-manager