apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: m4-gpu-monitoring
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m
  path: ./infrastructure/base/monitoring-configs
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
