apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-values
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: ykp-platform
data:
  values.yaml: |
    gitea:
      config:
        actions:
          ENABLED: true
