apiVersion: catalog.ykp.io/v1alpha1
kind: PlatformApp
metadata:
  name: traefik
  namespace: ykp-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: ykp-platform
spec:
  catalogAppId: traefik
  version: "v34.5.0"
  enabled: true
  targetNamespace: traefik
  lifecycle:
    preservePVCsOnDelete: true
    purgeCRDsOnDelete: false
  valuesOverrides:
    service:
      type: ClusterIP
    ports:
      web:
        port: 8000
        hostPort: 80
        expose:
          default: true
      websecure:
        port: 8443
        hostPort: 443
        expose:
          default: true
    nodeSelector:
      ingress-ready: "true"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.localhost`)
        entryPoints:
          - web
    providers:
      kubernetesGateway:
        enabled: false
