# permissions for end users to edit imageupdateautomations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imageupdateautomation-editor-role
rules:
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imageupdateautomations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imageupdateautomations/status
  verbs:
  - get
