apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-ingress
  interval: 5m
  values:
    ingressRoute:
      dashboard:
        enabled: true
        annotations: {}
        labels: {}
        matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
        services:
          - name: api@internal
            kind: Service
        entryPoints: ["web"]

