apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-ingress
  interval: 5m
  values:
    # Enables the dashboard in inSecure Mode
    api:
      dashboard: true
      insecure: true  # For dev only; use secure access in production
    ingressRoute:
      dashboard:
        enabled: true
        annotations: {}
        labels: {}
        matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
        services:
          - name: api@internal
            kind: Service
        entryPoints: ["web"]
        middlewares:
          - name: dashboard-auth

    # Creates a BasiAuth Middleware and Secret for the Dashboard Security
    extraObjects:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: dashboard-auth-secret
        type: kubernetes.io/basic-auth
        stringData:
          username: admin
          password: "P@ssw0rd@123"      # Replace with an Actual Password
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: dashboard-auth
        spec:
          basicAuth:
            secret: dashboard-auth-secret






