apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-ingress
  interval: 5m
  values:
    # Enables the dashboard in Secure Mode
    api:
      dashboard: true
      insecure: false

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.mangale.com.np`)
        entryPoints:
          - websecure
        middlewares:
          - name: dashboard-auth
        tls:
          secretName: traefik-tls

    # Creates a BasiAuth Middleware and Secret for the Dashboard Security
    extraObjects:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: dashboard-auth-secret
        type: kubernetes.io/basic-auth
        stringData:
          username: admin
          password: "P@ssw0rd@123"      # Replace with an Actual Password
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: dashboard-auth
        spec:
          basicAuth:
            secret: dashboard-auth-secret

    # We will route with Gateway API instead.
    ingressClass:
      enabled: false

    # Enable Gateway API Provider & Disables the KubernetesIngress provider
    # Providers tell Traefik where to find routing configuration.
    providers:
      kubernetesIngress:
        enabled: true
      kubernetesGateway:
        enabled: true


    # Enable Observability
    logs:
      general:
        level: INFO
      # This enables access logs, outputting them to Traefik's standard output by default. The [Access Logs Documentation](https://doc.traefik.io/traefik/observability/access-logs/) covers formatting, filtering, and output options.
      access:
        enabled: true

    # Enables Prometheus for Metrics
    metrics:
      prometheus:
        enabled: true
