apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minimal-git-server.yaml
  - ykp-auth.yaml
  - ykp-api.yaml
  - ykp-catalog.yaml
  - ykp-dashboard.yaml
  - ykp-k8s-dashboard.yaml
  - ykp-audit.yaml
  - ykp-idp.yaml
  - ykp-cloud-providers.yaml
  - ykp-shell.yaml
