apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins
  namespace: jenkins
spec:
  secretName: jenkins-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - mangale.com.np
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - jenkins.mangale.com.np
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
