---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.io
  namespace: jenkins
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgDAnA6RpIlxDJUgK46EmIeSvOB+hkQ3pxl2xk/CScR+UQ48McikJTylJqFkfqlL84HbXG6StEaQHJs5lQWOTGAomm6uuEqGg4D0IIOSCBbepSTkQJ3bFUzajzPN3p+ywOH8K5UCIwrnhpVburIoJQ5LyTkUUusg/QU/kjuYCXvs4eMZObzeknuZFY/avPqoooJlvb4iQwBV2N0rF06Ntw47Hb9dyO6yTMaQIWF/DPOS81Xk4kkncUgyOFUCy+u7n3hr7m9o30MJfaXIDjahe+Dg1UoYSmSA8IUavC4NDUy6YzceBv/kiibv41+Q7X1vtDlyZkF/Cs60e17p9V7D65cPU0Wyv8/gnX+UGTikhipATYCG9Au8FPbWOTahwByKGWc4pHweM+bXLW7Zdvpr0RI8s9TvvDVflyU1h4X5lKKW+75lquJF1hA3A+742tbJNwwPcQI/A6ZqoOwFmWXA12KunsmYgoFz1/ZjR+N+RnrcdqUi6tGKXRhJ7WyLxsR+OwaJEaN4m6XmkQqRHj/KQ2MY7e3spGHBcdubBHBqoaQ2HM7AaEpU3u+dm9F/GQyM7ODvP0OHnHMrFxgTrLmdiCj7UfMr16zQWhwH1TH384WIhfr6xYfGsvz/05Xh+Kk0h+R5NXS8FoNmUUmXHPTK5/h28BgATAWmchHAkLoRvT6EXmyYZKBGqU3KdmOcpAYNVjIdwr5jN//SNdALWzUjBWbhfxeBVfxfCCpUV3HeqqJ/pyyAal22rYOQS1ozv0uoc3E8xiaeG+sHnSlCFEWldy3NFekOvTIu0c3nhhND4J7ANkL19ORq2j2KqrHehuKusV8wQOCaCtwHxJU4lNcHiMLHrMTFeLJH4Mokqvw69kHOon3CGMQG5D6joTJm2dTHLsSihYBiugRQUyVk6RcAoiq8g3v4i2jGJOCJ
  template:
    metadata:
      creationTimestamp: null
      name: docker.io
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson