---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
  labels:
    app: jenkins
    component: persistent-volume-claim
    storage: nutanix-volume
# This PersistentVolumeClaim is used to request storage for Jenkins.
spec:
  storageClassName: nutanix-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
