apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-values
  namespace: ykp-system
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: ykp-platform
data:
  values.yaml: |
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
