apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ykp-session-secret
  namespace: ykp-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ykp-session-secret
    creationPolicy: Owner
  data:
    - secretKey: YKP_SESSION_SECRET
      remoteRef:
        key: ykp/session-secret
        property: secretKey
