apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: nginx
data:
  index.html: |
    <html>
      <head><title>Welcome</title></head>
      <body>
        <h1>app1</h1>
      </body>
    </html>