apiVersion: v1
kind: Service
metadata:
  name: macmon-host-metrics
  namespace: monitoring
  labels:
    app: macmon-host-metrics
spec:
  ports:
    - name: metrics
      port: 9101
      targetPort: 9101
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: macmon-host-metrics
  namespace: monitoring
  labels:
    app: macmon-host-metrics
subsets:
  - addresses:
      - ip: 192.168.5.2
    ports:
      - name: metrics
        port: 9101
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: macmon-host-monitor
  namespace: monitoring
  labels:
    app: macmon-host-metrics
spec:
  selector:
    matchLabels:
      app: macmon-host-metrics
  endpoints:
    - port: metrics
      interval: 5s
      scrapeTimeout: 3s
      path: /metrics
